#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Based on http://joshsymonds.com/blog/2014/06/12/shell-awesomeness-with-prezto/

# Add homebrew to the completion path
# fpath=("/usr/local/bin/" $fpath)

# why would you type 'cd dir' if you could just type 'dir'?
setopt AUTO_CD

# Now we can pipe to multiple outputs!
setopt MULTIOS

# This makes cd=pushd
setopt AUTO_PUSHD

# This will use named dirs when possible
setopt AUTO_NAME_DIRS

# If we have a glob this will expand it
setopt GLOB_COMPLETE
setopt PUSHD_MINUS

# No more annoying pushd messages...
setopt PUSHD_SILENT

# blank pushd goes to home
setopt PUSHD_TO_HOME

# this will ignore multiple directories for the stack.  Useful?  I dunno.
setopt PUSHD_IGNORE_DUPS

# 10 second wait if you do something that will delete everything.  I wish I'd had this before...
setopt RM_STAR_WAIT

# use magic (this is default, but it can't hurt!)
setopt ZLE

setopt NO_HUP

# only fools wouldn't do this ;-)
# export VISUAL="subl -n -w"
# export EDITOR="subl -n -w"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export VISUAL="vim"
  export EDITOR="vim"
else
	export VISUAL="subl -n -w"
	export EDITOR="subl -n -w"
fi

setopt IGNORE_EOF

# If I could disable Ctrl-s completely I would!
setopt NO_FLOW_CONTROL

# Keep echo "station" > station from clobbering station
setopt NO_CLOBBER

# Case insensitive globbing
setopt NO_CASE_GLOB

# Be Reasonable!
setopt NUMERIC_GLOB_SORT

# I don't know why I never set this before.
setopt EXTENDED_GLOB

# hows about arrays be awesome?  (that is, frew${cool}frew has frew surrounding all the variables, not just first and last
setopt RC_EXPAND_PARAM

# Who doesn't want home and end to work?
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line
bindkey '^[begin' beginning-of-line
bindkey '^[end' end-of-line

# Incremental search is elite!
bindkey -M vicmd "/" history-incremental-search-backward
bindkey -M vicmd "?" history-incremental-search-forward

# Search based on what you typed in already
bindkey -M vicmd "//" history-beginning-search-backward
bindkey -M vicmd "??" history-beginning-search-forward

bindkey "\eOP" run-help

# oh wow!  This is killer...  try it!
bindkey -M vicmd "q" push-line

# it's like, space AND completion.  Gnarlbot.
bindkey -M viins ' ' magic-space

# Add Postgres app bin to path
export PATH=/Applications/Postgres.app/Contents/Versions/9.3/bin:${PATH}

# Add bin dirs to path
export PATH=./bin:/usr/local/bin:/usr/local/sbin:${PATH}

# Set Go lang variables
export GOPATH=$HOME/.go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/opt/go/libexec/bin

# Add npm modules path to Node.js
export PATH=/usr/local/share/npm/bin:${PATH}
export NODE_PATH=`which node`

# Configure vagrant
export VAGRANT_DEFAULT_PROVIDER=vmware_fusion

# Configure Ansible
export PATH=/Users/sebastiaan/dev/src/ansible/bin:${PATH}
source $HOME/dev/src/ansible/hacking/env-setup >& /dev/null
export ANSIBLE_TRANSPORT=ssh
# export ANSIBLE_HOSTS=~/ansible_hosts

export JAVA_HOME="$(/usr/libexec/java_home)"
# export PATH=/usr/local/share/python:$PATH

# Optimize Ruby for Rails apps
# https://gist.github.com/nilcolor/4602764
# export RUBY_GC_MALLOC_LIMIT=60000000
# export RUBY_FREE_MIN=200000

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# Add ability to load gem activation information from a gemdeps file (Gemfile, Isolate, gem.deps.rb).
# Set RUBYGEMS_GEMDEPS=path to have it loaded. Use - as the path to autodetect (current and parent directories are searched).
# export RUBYGEMS_GEMDEPS=-

# Aliases
alias gcm='git checkout master'
alias pasta='passenger start'
alias pasto='passenger stop'

eval "$(direnv hook zsh)"
chruby ruby-2.2.0

# tmuxinator autocomplete
source ~/.tmuxinator/tmuxinator.zsh
